### ISSUE TITLE
Please respect semantic versioning, 3.4.2 dropped py36 support

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/filelock#131] opened 2022-01-04 14:48 UTC
I do not think it is unreasonable to expect a bump of at **least the minor version** when dropping a supported python version (3.6) instead of just releasing a patch.

Not following the semantic versioning, or not doing code reviews is a bad practice that may alienate other consumers.

I would have being enough to version it `3.5.0` or even `4.0.0` as it clearly is a breaking change.

Related:
* https://github.com/tox-dev/py-filelock/pull/125
* https://github.com/tox-dev/py-filelock/releases/tag/3.4.2

**Comment by gaborbernat** [comment] 2022-01-04 14:59
Duplicate of https://github.com/tox-dev/py-filelock/issues/126

**Closed as completed by gaborbernat** 2022-01-04 14:59 UTC
