### ISSUE TITLE
pylint error abstract-class-instantiated since version 3.3.0

### ISSUE THREAD

**Issue by PhilippSelenium** [tox-dev/filelock#118] opened 2021-11-09 14:52 UTC
When using the simple example:

```
# test.py
from filelock import FileLock

lock = FileLock("/tmp/foo.lock", "bar")
with lock:
    pass
```
```
pylint test.py
```

I get the pylint errors: 
```
test.py:3:7: E0110: Abstract class 'WindowsFileLock' with abstract methods instantiated (abstract-class-instantiated)
test.py:3:7: E0110: Abstract class 'UnixFileLock' with abstract methods instantiated (abstract-class-instantiated)
```

* This could also be a false positive of pylint
* Yes, I could ignore the errors
* I do not understand why this started happening here: https://github.com/tox-dev/py-filelock/compare/3.2.0...3.3.0

**Comment by gaborbernat** [comment] 2021-11-09 15:11
Duplicate of https://github.com/tox-dev/py-filelock/issues/102

**Closed as completed by gaborbernat** 2021-11-09 15:11 UTC
